version: '3'
services:
  post_management_service:
    image: vinicius14/post_management
    build: .
    container_name: app_post_management
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: posts
    ports:
      - "3000:3000"
    volumes:
      - .:/src/app
    command: /bin/bash -c "npx sequelize-cli db:migrate && npm run dev"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: posts
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
volumes:
  db_data: